steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build' 
  - '-t' 
  - 'gcr.io/$PROJECT_ID/cj-test-docker' 
  - '--label' 
  - 'org.opencontainers.image.revision=$COMMIT_SHA' 
  - '--label' 
  - 'org.opencontainers.image.source=docker/Dockerfile' 
  - '-f' 
  - 'docker/Dockerfile' 
  - '.'
images: ['gcr.io/$PROJECT_ID/linking-test-gcr']
